### ISSUE TITLE
unexpected keyword argument 'source_address'

### ISSUE THREAD

**Issue by NGSegovia** [cdent/wsgi-intercept#34]
Since version 1.0.0 wsgi-intercept fails with httplib2_intercept request.
With version 0.10.3 work properly. Here are my test:
[wsgi-intercept-issue.txt](https://github.com/cdent/wsgi-intercept/files/82718/wsgi-intercept-issue.txt)

Congratulations for your project. Thanks!

**Comment by cdent** [comment]
This is happening because you're using Python 2.6. wsgi-intercept 1.0.0 dropped support for python 2.6.  It's only tested on 2.7 and 3.3 and beyond. If you need to continue using 2.6 for some reason then you'll need to pin to version 0.10.3.

In the tests below `foo.py` is your example test put into a file with a couple of asserts at the end. In the 2.7 example the lack of output or error means everything worked.

```shell
shine:/tmp $ foobar/bin/python2.6 /tmp/foo.py 
Traceback (most recent call last):
  File "/tmp/foo.py", line 12, in <module>
    resp, content = http.request(url)
  File "/private/tmp/foobar/lib/python2.6/site-packages/httplib2/__init__.py", line 1491, in request
    proxy_info=proxy_info)
  File "/private/tmp/foobar/lib/python2.6/site-packages/wsgi_intercept/httplib2_intercept.py", line 24, in __init__
    timeout=timeout, source_address=source_address)
TypeError: __init__() got an unexpected keyword argument 'source_address'
shine:/tmp $ python2.7 /tmp/foo.py 
```

If there's some pressing reason why 2.6 support is still important to maintain, please let me know in a respose to this comment. If not, please get off python 2.6.6; there have been important security fixes (see [2.6.9](https://www.python.org/download/releases/2.6.9/)) and 2.6 is no longer a supported version of Python.

**Comment by NGSegovia** [comment]
Thank you for your answer and you recommendations @cdent!
For now i can't move to Python 2.7, so i'll stay on version 0.10.3.

I was wrong because in the documentation (http://wsgi-intercept.readthedocs.org/en/latest/),  on the history section still mentions Python 2.6

**Comment by cdent** [comment]
Oh, sorry about, thanks for letting me know. It turns out that the docs build jobs at readthedocs were not working properly. The source had been updated but not the published docs. I'm fixing the docs jobs now.
